### PR TITLE
🐛 Fix `fc.option` nil frequency 

### LINKED ISSUE #6063: Cannot create 100%-undefined Options
## 🐛 Bug Report

The [option documentation](https://fast-check.dev/docs/core-blocks/arbitraries/combiners/any/#option) states:

> probability to build the nil value is of 1 / freq

This would imply that passing `{ freq: 1 }` would give an option that always produces nil. Currently, there is no working way to produce such an arbitrary.

## To Reproduce
```
describe('option arbitrary', () => {
  it.prop([fc.option(fc.constant(true), { freq: 1 })])('should always return nil if freq = 1', (o) => {
    expect(o).toEqual(null);
  });
});
```

```
option arbitrary › should always return nil if freq = 1 (with seed=-1040376467)

    Property failed after 3 tests
    { seed: -1040376467, path: "2", endOnFailure: true }
    Counterexample: [true]
    Shrunk 0 time(s)
    Got error: expect(received).toEqual(expected) // deep equality

    Expected: null
    Received: true
```

## Expected behavior

```
  option arbitrary
    ✓ should always return nil if freq = 1 (with seed=-1040376467) (4 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
```

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| @fast-check/jest           |  1.6.2          |
| @fast-check           |  3.23.2        |
| node                 |      22.14.0      |
| TypeScript\*         |    5.8.2        |

\*Only for TypeScript's users

### PR DESCRIPTION
**Pull request by gruhn**
Closes #6063 

**Description**

Previously, `fc.option` assigned weight 1 to the nil Arbitrary and
weight `freq` to the value Arbitrary. With that nil is generated with
probability:

    P(nil) = nil_weight / (value_weight + nil_weight)
           = 1 / (freq + 1)

The intended probability was `1 / freq` though. This is corrected by
assigning weight `freq - 1` to the value Arbitrary. With that we get:

    P(nil) = nil_weight / (value_weight + nil_weight)
           = 1 / (freq - 1 + 1)
           = 1 / freq

    P(value) = value_weight / (value_weight + nil_weight)
             = (freq - 1) / (freq - 1 + 1)
             = (freq - 1) / freq
             = 1 - (1 / freq)

Here are some statistics, computed with:

```typescript
  for (const freq of [1,2,3,4,5,6,10,20]) {
    console.debug({ freq, expected_null_prop: `${100/freq}%` })
    fc.statistics(option(constant(true), { freq }), String, { numRuns: 10_000 })
    console.debug('')
  }
```

Before the change: 

    { freq: 1, expected_null_prop: '100%' }
    true..50.13%
    null..49.87%
    
    { freq: 2, expected_null_prop: '50%' }
    true..66.72%
    null..33.28%
    
    { freq: 3, expected_null_prop: '33.333333333333336%' }
    true..74.65%
    null..25.35%
    
    { freq: 4, expected_null_prop: '25%' }
    true..79.48%
    null..20.52%
    
    { freq: 5, expected_null_prop: '20%' }
    true..83.56%
    null..16.44%
    
    { freq: 6, expected_null_prop: '16.666666666666668%' }
    true..85.75%
    null..14.25%
    
    { freq: 10, expected_null_prop: '10%' }
    true..91.06%
    null...8.94%
    
    { freq: 20, expected_null_prop: '5%' }
    true..95.24%
    null...4.76%

After the change:
    
    { freq: 1, expected_null_prop: '100%' }
    null..100.00%
    
    { freq: 2, expected_null_prop: '50%' }
    true..50.27%
    null..49.73%
    
    { freq: 3, expected_null_prop: '33.333333333333336%' }
    true..66.43%
    null..33.57%
    
    { freq: 4, expected_null_prop: '25%' }
    true..75.01%
    null..24.99%
    
    { freq: 5, expected_null_prop: '20%' }
    true..80.64%
    null..19.36%
    
    { freq: 6, expected_null_prop: '16.666666666666668%' }
    true..83.81%
    null..16.19%
    
    { freq: 10, expected_null_prop: '10%' }
    true..89.89%
    null..10.11%
    
    { freq: 20, expected_null_prop: '5%' }
    true..94.78%
    null...5.22%

**Checklist** — _Don't delete this checklist and make sure you do the following before opening the PR_

- [x] The name of my PR follows [gitmoji](https://gitmoji.dev/) specification
- [x] My PR references one of several related issues (if any)
  - [x] New features or breaking changes must come with an associated Issue or Discussion
  - [x] My PR does not add any new dependency without an associated Issue or Discussion
- [x] My PR includes bumps details, please run `pnpm run bump` and flag the impacts properly
- [x] My PR adds relevant tests and they would have failed without my PR (when applicable)

**Advanced**

- [x] Category: 🐛 Fix a bug
- [x] Impacts: Changes probability distribution of `fc.option`

### CODE REVIEW

**Comment by gruhn** [comment]
Looks like some regression tests are failing. Will check tomorrow.

File: packages/fast-check/src/arbitrary/option.ts [hunk 1]
```diff
@@ -1,19 +1,22 @@
 import { constant } from './constant';
 import type { Arbitrary } from '../check/arbitrary/definition/Arbitrary';
-import type { _Constraints as FrequencyContraints } from './_internals/FrequencyArbitrary';
+import type { _Constraints as FrequencyConstraints } from './_internals/FrequencyArbitrary';
```
Comment (gruhn) [inline packages/fast-check/src/arbitrary/option.ts:3]: Fixed typo. This is just a local alias so renaming should be fine I guess.

File: packages/fast-check/src/arbitrary/option.ts [hunk 2]
```diff
@@ -1,19 +1,22 @@
...
 /**
  * Constraints to be applied on {@link option}
  * @remarks Since 2.2.0
  * @public
  */
 export interface OptionConstraints<TNil = null> {
   /**
-   * The probability to build a nil value is of `1 / freq`
+   * The probability to build a nil value is of `1 / freq`.
+   * If `freq` is `0`, then nil is never generated.
```
Comment (gruhn) [inline packages/fast-check/src/arbitrary/option.ts:19]: Since 1/0 is commonly not defined but `freq=0` is supported so I thought it's worth explaining that special case.

File: packages/fast-check/src/arbitrary/option.ts [hunk 3]
```diff
@@ -61,14 +64,16 @@ export function option<T, TNil = null>(
   arb: Arbitrary<T>,
   constraints: OptionConstraints<TNil> = {},
 ): Arbitrary<T | TNil> {
-  const freq = constraints.freq == null ? 5 : constraints.freq;
+  const freq = constraints.freq == null ? 6 : constraints.freq;
```
Comment (gruhn) [inline packages/fast-check/src/arbitrary/option.ts:64]: Incremented the default value to maintain the previous default distribution.

File: packages/fast-check/test/unit/arbitrary/option.spec.ts [hunk 4]
```diff
@@ -98,7 +99,7 @@ describe('option', () => {
 
 describe('option (integration)', () => {
   type Extra = { freq?: number };
-  const extraParameters = fc.record({ freq: fc.nat() }, { requiredKeys: [] });
+  const extraParameters = fc.record({ freq: fc.integer({ min: 1 }) }, { requiredKeys: [] });
```
Comment (gruhn) [inline packages/fast-check/test/unit/arbitrary/option.spec.ts:102]: `freq=0` is not meant to be supported right?

File: packages/fast-check/src/arbitrary/option.ts (hunk 1 above)
Comment (dubzzz) [reply packages/fast-check/src/arbitrary/option.ts:3]: Definitely fine

File: packages/fast-check/src/arbitrary/option.ts [hunk 5]
```diff
@@ -13,8 +13,8 @@ import { safeHasOwnProperty } from '../utils/globals';
  */
 export interface OptionConstraints<TNil = null> {
   /**
-   * The probability to build a nil value is of `1 / freq`
```
Comment (dubzzz) [inline packages/fast-check/src/arbitrary/option.ts:16]: The fact that we are changing the default makes me think that it should not be changed into a minor/patch without extra care. What I did in such cases for the previous version of fast-check has been to introduce a `next:boolean` in the constraints object. When true we toggle on the new behavior, otherwise we preserve the old one 

For the record, I may plan a major sooner than expected to be able to drop cjs+esm bundlings.

File: packages/fast-check/test/unit/arbitrary/option.spec.ts (hunk 4 above)
Comment (dubzzz) [reply packages/fast-check/test/unit/arbitrary/option.spec.ts:102]: Given the doc string, I'd say the same: not supported for zero

**Comment by dubzzz** [comment]
I think the CI might be partially broken, I'll try to fix it. It might not be related to your PR

File: packages/fast-check/src/arbitrary/option.ts (hunk 5 above)
Comment (gruhn) [reply packages/fast-check/src/arbitrary/option.ts:16]: Just to be clear: I changed the default value so it matches the default before the change. So any user using `fc.option` without `freq` parameter should see no change. If you do use `freq` you could observe a change though.

**Comment by dubzzz** [comment]
Just updated your branch given I should have fixed the CI

**Review by dubzzz — APPROVED** [review]
