### PR TITLE
🐛(vitest) Fix runtime exception with `test.each`

### LINKED ISSUE #6798: test.each in Vitest sees a TypeError
### Bug description

Using `test.each` from `@fast-check/vitest` leads to a `TypeError: Cannot read properties of undefined (reading 'withContext')` error.

### To reproduce

```ts
import { test } from '@fast-check/vitest'
import { expect } from 'vitest'

test.each([1, 2])('my test', i => {
  expect(i).toBe(i)
})
```

### Expected behavior

The test runs the same as

```
import { expect, test } from 'vitest'

test.each([1, 2])('my test', i => {
  expect(i).toBe(i)
})
```

### Environment

```text
node: v24.13.0
typescript: 5.9.3
fast-check: 3.23.2
@fast-check/vitest: 0.3.0
```

### PR DESCRIPTION
**Pull request by dubzzz**
When building the enriched test function, the each method was extracted from testFnExtended (created by createTaskCollector) without proper this binding. This caused a 'Cannot read properties of undefined (reading withContext)' error when calling test.each().

Fix: use the original vitest testFn's each method with proper binding, since each is a standard vitest feature that doesn't need fast-check wrapping.

Fixes #6798

## Description

Fixes #issue-number

## Checklist

— _Don't delete this checklist and make sure you do the following before opening the PR_

- [ ] I have a full understanding of every line in this PR — whether the code was hand-written, AI-generated, copied from external sources or produced by any other tool
- [ ] I flagged the impact of my change (minor / patch / major) either by running `pnpm run bump` or by following the instructions from the changeset bot
- [ ] I kept this PR focused on a single concern and did not bundle unrelated changes
- [ ] I followed the [gitmoji](https://gitmoji.dev/) specification for the name of the PR, including the package scope (e.g. `🐛(vitest) Something...`) when the change targets a package other than `fast-check`
- [ ] I added relevant tests and they would have failed without my PR (when applicable)

### CODE REVIEW

File: packages/vitest/src/internals/TestBuilder.ts [hunk 1]
```diff
@@ -146,7 +146,7 @@ export function buildTest<T extends (...args: any[]) => any>(
       extraKeys[key] =
         key !== 'each'
           ? buildTest((testFn as any)[key], testFnExtended[key] as any, fc, new Set([...ancestors, key]))
```
Comment (dubzzz) [inline packages/vitest/src/internals/TestBuilder.ts:148]: @claude probably worth binding this one too

File: packages/vitest/src/internals/TestBuilder.ts [hunk 2]
```diff
@@ -145,8 +145,8 @@ export function buildTest<T extends (...args: any[]) => any>(
       atLeastOneExtra = true;
       extraKeys[key] =
         key !== 'each'
-          ? buildTest((testFn as any)[key], testFnExtended[key] as any, fc, new Set([...ancestors, key]))
-          : testFnExtended[key];
+          ? buildTest(((testFn as any)[key] as (...args: unknown[]) => unknown).bind(testFn), testFnExtended[key] as any, fc, new Set([...ancestors, key]))
+          : ((testFn as any)[key] as (...args: unknown[]) => unknown).bind(testFn);
```
Comment (dubzzz) [inline packages/vitest/src/internals/TestBuilder.ts]: @claude bind extended fn too?

**Comment by dubzzz** [comment]
@claude woops it broke many tests, please find why and fix


⎯⎯⎯⎯⎯⎯ Failed Tests 14 ⎯⎯⎯⎯⎯⎯⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'test'[2m > at depth 1[2m > should support test.concurrent.prop
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '✓ generated.spec.mjs'

- Expected
+ Received

- ✓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: test.concurrent.prop is not a function
+  ❯ generated.spec.mjs:5:23
+       3| import {test as runner} from '@fast-check/vitest';
+       4|
+       5|     runner.concurrent.prop([
+        |                       ^
+       6|      fc.string(),
+       7|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectPass test/vitest-fast-check.spec.ts:[2m558:15
    556|
    557| function expectPass(out: string): void {
    558|   expect(out).toContain('✓ ' + specFileName);
       |               ^
    559| }
    560|
 [2m❯ test/vitest-fast-check.spec.ts:[2m71:7

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/14]⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'test'[2m > at depth 1[2m > should support test.only.prop
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '✓ generated.spec.mjs'

- Expected
+ Received

- ✓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: test.only.prop is not a function
+  ❯ generated.spec.mjs:5:17
+       3| import {test as runner} from '@fast-check/vitest';
+       4|
+       5|     runner.only.prop([
+        |                 ^
+       6|      fc.string(),
+       7|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectPass test/vitest-fast-check.spec.ts:[2m558:15
    556|
    557| function expectPass(out: string): void {

    558|   expect(out).toContain('✓ ' + specFileName);
       |               ^
    559| }
    560|
 [2m❯ test/vitest-fast-check.spec.ts:[2m101:7

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/14]⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'test'[2m > at depth 1[2m > should support test.skip.prop
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '↓ generated.spec.mjs'

- Expected
+ Received

- ↓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: test.skip.prop is not a function
+  ❯ generated.spec.mjs:5:17
+       3| import {test as runner} from '@fast-check/vitest';
+       4|
+       5|     runner.skip.prop([
+        |                 ^
+       6|      fc.string(),
+       7|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectSkip test/vitest-fast-check.spec.ts:[2m566:15
    564|
    565| function expectSkip(out: string): void {
    566|   expect(out).toContain('↓ ' + specFileName);
       |               ^
    567| }
    568|
 [2m❯ test/vitest-fast-check.spec.ts:[2m116:7

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[3/14]⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'test'[2m > at depth 1[2m > should support test.todo.prop
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '↓ generated.spec.mjs'

- Expected
+ Received

- ↓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: test.todo.prop is not a function
+  ❯ generated.spec.mjs:5:17
+       3| import {test as runner} from '@fast-check/vitest';
+       4|
+       5|     runner.todo.prop([
+        |                 ^
+       6|      fc.string(),
+       7|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectSkip test/vitest-fast-check.spec.ts:[2m566:15
    564|
    565| function expectSkip(out: string): void {
    566|   expect(out).toContain('↓ ' + specFileName);
       |               ^
    567| }
    568|
 [2m❯ test/vitest-fast-check.spec.ts:[2m131:7

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[4/14]⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'test'[2m > at depth 1[2m > should call beforeEach, afterEach and clean-ups the same number of times even in failure cases
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '✓ generated.spec.mjs'

- Expected
+ Received

- ✓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: test.fails.prop is not a function
+  ❯ generated.spec.mjs:14:18
+      12|      probes.push(`afterEach`);
+      13|     });
+      14|     runner.fails.prop([fc.string()])("property", (s) => {
+        |                  ^
+      15|      probes.push(`predicate`);
+      16|      return s.length % 2 === 0;
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectPass test/vitest-fast-check.spec.ts:[2m558:15
    556|
    557| function expectPass(out: string): void {
    558|   expect(out).toContain('✓ ' + specFileName);
       |               ^
    559| }
    560|
 [2m❯ test/vitest-fast-check.spec.ts:[2m309:9

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[5/14]⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'test'[2m > at depth strictly above 1[2m > should support test.concurrent.fails.skip.prop
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '↓ generated.spec.mjs'

- Expected
+ Received

- ↓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: Cannot read properties of undefined (reading 'skip')
+  ❯ generated.spec.mjs:5:29
+       3| import {test as runner} from '@fast-check/vitest';
+       4|
+       5|     runner.concurrent.fails.skip.prop([
+        |                             ^
+       6|      fc.string(),
+       7|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectSkip test/vitest-fast-check.spec.ts:[2m566:15
    564|
    565| function expectSkip(out: string): void {
    566|   expect(out).toContain('↓ ' + specFileName);
       |               ^
    567| }
    568|
 [2m❯ test/vitest-fast-check.spec.ts:[2m384:7

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[6/14]⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'test'[2m > at depth strictly above 1[2m > should support test.concurrent.fails.todo.prop
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '↓ generated.spec.mjs'

- Expected
+ Received

- ↓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: Cannot read properties of undefined (reading 'todo')
+  ❯ generated.spec.mjs:5:29
+       3| import {test as runner} from '@fast-check/vitest';
+       4|
+       5|     runner.concurrent.fails.todo.prop([
+        |                             ^
+       6|      fc.string(),
+       7|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectSkip test/vitest-fast-check.spec.ts:[2m566:15
    564|
    565| function expectSkip(out: string): void {
    566|   expect(out).toContain('↓ ' + specFileName);
       |               ^
    567| }
    568|
 [2m❯ test/vitest-fast-check.spec.ts:[2m399:7

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[7/14]⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'it'[2m > at depth 1[2m > should support it.concurrent.prop
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '✓ generated.spec.mjs'

- Expected
+ Received

- ✓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: it.concurrent.prop is not a function
+  ❯ generated.spec.mjs:6:23
+       4| describe('test suite', () => {
+       5|
+       6|     runner.concurrent.prop([
+        |                       ^
+       7|      fc.string(),
+       8|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectPass test/vitest-fast-check.spec.ts:[2m558:15
    556|
    557| function expectPass(out: string): void {
    558|   expect(out).toContain('✓ ' + specFileName);
       |               ^
    559| }
    560|
 [2m❯ test/vitest-fast-check.spec.ts:[2m71:7

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[8/14]⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'it'[2m > at depth 1[2m > should support it.only.prop
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '✓ generated.spec.mjs'

- Expected
+ Received

- ✓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: it.only.prop is not a function
+  ❯ generated.spec.mjs:6:17
+       4| describe('test suite', () => {
+       5|
+       6|     runner.only.prop([
+        |                 ^
+       7|      fc.string(),
+       8|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectPass test/vitest-fast-check.spec.ts:[2m558:15
    556|
    557| function expectPass(out: string): void {
    558|   expect(out).toContain('✓ ' + specFileName);
       |               ^
    559| }
    560|
 [2m❯ test/vitest-fast-check.spec.ts:[2m101:7

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[9/14]⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'it'[2m > at depth 1[2m > should support it.skip.prop
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '↓ generated.spec.mjs'

- Expected
+ Received

- ↓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: it.skip.prop is not a function
+  ❯ generated.spec.mjs:6:17
+       4| describe('test suite', () => {
+       5|
+       6|     runner.skip.prop([
+        |                 ^
+       7|      fc.string(),
+       8|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectSkip test/vitest-fast-check.spec.ts:[2m566:15
    564|
    565| function expectSkip(out: string): void {
    566|   expect(out).toContain('↓ ' + specFileName);
       |               ^
    567| }
    568|
 [2m❯ test/vitest-fast-check.spec.ts:[2m116:7

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[10/14]⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'it'[2m > at depth 1[2m > should support it.todo.prop
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '↓ generated.spec.mjs'

- Expected
+ Received

- ↓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: it.todo.prop is not a function
+  ❯ generated.spec.mjs:6:17
+       4| describe('test suite', () => {
+       5|
+       6|     runner.todo.prop([
+        |                 ^
+       7|      fc.string(),
+       8|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectSkip test/vitest-fast-check.spec.ts:[2m566:15
    564|
    565| function expectSkip(out: string): void {
    566|   expect(out).toContain('↓ ' + specFileName);
       |               ^
    567| }
    568|
 [2m❯ test/vitest-fast-check.spec.ts:[2m131:7

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[11/14]⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'it'[2m > at depth 1[2m > should call beforeEach, afterEach and clean-ups the same number of times even in failure cases
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '✓ generated.spec.mjs'

- Expected
+ Received

- ✓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: it.fails.prop is not a function
+  ❯ generated.spec.mjs:15:18
+      13|      probes.push(`afterEach`);
+      14|     });
+      15|     runner.fails.prop([fc.string()])("property", (s) => {
+        |                  ^
+      16|      probes.push(`predicate`);
+      17|      return s.length % 2 === 0;
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectPass test/vitest-fast-check.spec.ts:[2m558:15
    556|
    557| function expectPass(out: string): void {
    558|   expect(out).toContain('✓ ' + specFileName);
       |               ^
    559| }
    560|
 [2m❯ test/vitest-fast-check.spec.ts:[2m309:9

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[12/14]⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'it'[2m > at depth strictly above 1[2m > should support it.concurrent.fails.skip.prop
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '↓ generated.spec.mjs'

- Expected
+ Received

- ↓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: Cannot read properties of undefined (reading 'skip')
+  ❯ generated.spec.mjs:6:29
+       4| describe('test suite', () => {
+       5|
+       6|     runner.concurrent.fails.skip.prop([
+        |                             ^
+       7|      fc.string(),
+       8|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectSkip test/vitest-fast-check.spec.ts:[2m566:15
    564|
    565| function expectSkip(out: string): void {
    566|   expect(out).toContain('↓ ' + specFileName);
       |               ^
    567| }
    568|
 [2m❯ test/vitest-fast-check.spec.ts:[2m384:7

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[13/14]⎯

 FAIL   @fast-check/vitest  test/vitest-fast-check.spec.ts[2m > 'it'[2m > at depth strictly above 1[2m > should support it.concurrent.fails.todo.prop
AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '↓ generated.spec.mjs'

- Expected
+ Received

- ↓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: Cannot read properties of undefined (reading 'todo')
+  ❯ generated.spec.mjs:6:29
+       4| describe('test suite', () => {
+       5|
+       6|     runner.concurrent.fails.todo.prop([
+        |                             ^
+       7|      fc.string(),
+       8|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 [2m❯ expectSkip test/vitest-fast-check.spec.ts:[2m566:15
    564|
    565| function expectSkip(out: string): void {
    566|   expect(out).toContain('↓ ' + specFileName);
       |               ^
    567| }
    568|
 [2m❯ test/vitest-fast-check.spec.ts:[2m399:7

[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[14/14]⎯

[2m Test Files  1 failed[2m | 81 passed (82)
[2m      Tests  14 failed[2m | 1075 passed (1089)
[2m   Start at  22:44:30
[2m   Duration  127.74s[2m (transform 2.95s, setup 2.28s, import 7.35s, tests 229.20s, environment 350ms)


AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '✓ generated.spec.mjs'

- Expected
+ Received

- ✓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: test.concurrent.prop is not a function
+  ❯ generated.spec.mjs:5:23
+       3| import {test as runner} from '@fast-check/vitest';
+       4|
+       5|     runner.concurrent.prop([
+        |                       ^
+       6|      fc.string(),
+       7|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 ❯ expectPass test/vitest-fast-check.spec.ts:558:15
 ❯ test/vitest-fast-check.spec.ts:71:7



AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '✓ generated.spec.mjs'

- Expected
+ Received

- ✓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: test.only.prop is not a function
+  ❯ generated.spec.mjs:5:17
+       3| import {test as runner} from '@fast-check/vitest';
+       4|
+       5|     runner.only.prop([
+        |                 ^
+       6|      fc.string(),
+       7|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 ❯ expectPass test/vitest-fast-check.spec.ts:558:15
 ❯ test/vitest-fast-check.spec.ts:101:7



AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '↓ generated.spec.mjs'

- Expected
+ Received

- ↓ generated.spec.mjs
+ stderr | generated.spec.mjs
+ Importing from "vitest/suite" is deprecated since Vitest 4.1. Please use static methods of "TestRunner" from the "vitest" entry point instead: e.g., `TestRunner.getCurrentTest()`.
+
+
+ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
+
+  FAIL  generated.spec.mjs [ generated.spec.mjs ]
+ TypeError: test.skip.prop is not a function
+  ❯ generated.spec.mjs:5:17
+       3| import {test as runner} from '@fast-check/vitest';
+       4|
+       5|     runner.skip.prop([
+        |                 ^
+       6|      fc.string(),
+       7|      fc.string(),
+
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
+
+

 ❯ expectSkip test/vitest-fast-check.spec.ts:566:15
 ❯ test/vitest-fast-check.spec.ts:116:7



AssertionError: expected 'stderr | generated.spec.mjs\nImportin…' to contain '↓ generate

File: packages/vitest/src/internals/TestBuilder.ts [hunk 3]
```diff
@@ -143,10 +143,13 @@ export function buildTest<T extends (...args: any[]) => any>(
     const key = unsafeKey as keyof typeof testFnExtended & string;
     if (!ancestors.has(key) && typeof testFnExtended[key] === 'function') {
       atLeastOneExtra = true;
+      const testFnChild = testFn != null ? (testFn as any)[key] : undefined;
```
Comment (dubzzz) [inline packages/vitest/src/internals/TestBuilder.ts]: @claude drop the check for not null as it was always true in the past

Comment (dubzzz) [reply packages/vitest/src/internals/TestBuilder.ts]: @claude apply same logic for extended too, need to bind when possible

Comment (dubzzz) [reply packages/vitest/src/internals/TestBuilder.ts]: @claude try to push what you suggested above

File: packages/vitest/src/internals/TestBuilder.ts [hunk 4]
```diff
@@ -143,10 +143,21 @@ export function buildTest<T extends (...args: any[]) => any>(
...
+      const testFnChildBound =
+        typeof testFnChild === 'function' ? (testFnChild as (...args: unknown[]) => unknown).bind(testFn) : testFnChild;
+      const testFnExtendedChild = testFnExtended[key];
```
Comment (dubzzz) [inline packages/vitest/src/internals/TestBuilder.ts]: @claude keep extended fn logic as simple as the one for non extended one. Drop this define property that you added in last commit. Make sure to run pnpm format before commit

File: packages/vitest/src/internals/TestBuilder.ts [hunk 5]
```diff
@@ -143,10 +143,18 @@ export function buildTest<T extends (...args: any[]) => any>(
     const key = unsafeKey as keyof typeof testFnExtended & string;
     if (!ancestors.has(key) && typeof testFnExtended[key] === 'function') {
       atLeastOneExtra = true;
+      const testFnChild = testFn != null ? (testFn as any)[key] : undefined;
```
Comment (dubzzz) [inline packages/vitest/src/internals/TestBuilder.ts]:
```suggestion
      const testFnChild = (testFn as any)[key];
```

File: packages/vitest/src/internals/TestBuilder.ts [hunk 6]
```diff
@@ -143,10 +143,18 @@ export function buildTest<T extends (...args: any[]) => any>(
...
+      const testFnExtendedChildBound =
+        typeof testFnExtendedChild === 'function'
+          ? (testFnExtendedChild as (...args: unknown[]) => unknown).bind(testFnExtended)
+          : testFnExtendedChild;
       extraKeys[key] =
         key !== 'each'
-          ? buildTest((testFn as any)[key], testFnExtended[key] as any, fc, new Set([...ancestors, key]))
-          : testFnExtended[key];
+          ? buildTest(testFnChildBound, testFnExtendedChildBound as any, fc, new Set([...ancestors, key]))
+          : testFnChildBound;
```
Comment (dubzzz) [inline packages/vitest/src/internals/TestBuilder.ts]:
```suggestion
          : testFnExtendedChildBound;
```

File: packages/vitest/src/internals/TestBuilder.ts [hunk 7]
```diff
@@ -143,10 +143,18 @@ export function buildTest<T extends (...args: any[]) => any>(
...
     if (!ancestors.has(key) && typeof testFnExtended[key] === 'function') {
       atLeastOneExtra = true;
+      const testFnChild = (testFn as any)[key];
+      const testFnChildBound =
+        typeof testFnChild === 'function' ? (testFnChild as (...args: unknown[]) => unknown).bind(testFn) : testFnChild;
+      const testFnExtendedChild = testFnExtended[key];
+      const testFnExtendedChildBound =
+        typeof testFnExtendedChild === 'function'
+          ? (testFnExtendedChild as (...args: unknown[]) => unknown).bind(testFnExtended)
+          : testFnExtendedChild;
```
Comment (dubzzz) [inline packages/vitest/src/internals/TestBuilder.ts]:
```suggestion
```

File: packages/vitest/src/internals/TestBuilder.ts [hunk 8]
```diff
@@ -143,10 +143,18 @@ export function buildTest<T extends (...args: any[]) => any>(
...
       extraKeys[key] =
         key !== 'each'
-          ? buildTest((testFn as any)[key], testFnExtended[key] as any, fc, new Set([...ancestors, key]))
-          : testFnExtended[key];
+          ? buildTest(testFnChildBound, testFnExtendedChildBound as any, fc, new Set([...ancestors, key]))
+          : testFnExtendedChildBound;
```
Comment (dubzzz) [inline packages/vitest/src/internals/TestBuilder.ts]:
```suggestion
          ? buildTest((testFn as any)[key], testFnExtended[key] as any, fc, new Set([...ancestors, key])) 
          : testFn[key];
```

**Comment by rushelex** [comment]
@dubzzz Check out PR https://github.com/dubzzz/fast-check/pull/6910 with a fix for this PR
